
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjwauhgoyjwcqylbmpaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqd2F1aGdveWp3Y3F5bGJtcGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDI2NDMsImV4cCI6MjA2MTYxODY0M30.eJMFqj9x6pqR8x99njTxrY9fgrmXXq9xkqODEGW9Emk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});
